;--------------------------------------------------;
;---------------------- SALA ----------------------;
;--------------------------------------------------;

(defclass Sala
    (is-a USER)
    (role concrete)
    (pattern-match reactive)
    (slot Nombre
        (type STRING)
        (create-accessor read-write))
)

;--------------------------------------------------;
;--------------------- CUADRO ---------------------;
;--------------------------------------------------;

(defclass Cuadro
    (is-a USER)
    (role concrete)
    (pattern-match reactive)
    (slot Titulo
        (type STRING)
        (create-accessor read-write))
    (slot AnyCreacion
        (type INTEGER)
        (create-accessor read-write))
    (slot Pintado_por   ;Relacion con Pintor
        (type INSTANCE)
        (create-accessor read-write))
    (slot Epoca
        (type STRING)
        (create-accessor read-write))
    (slot Estilo
        (type STRING)
        (create-accessor read-write))
    (slot Tematica
        (type STRING)
        (create-accessor read-write))
    (slot Dimensiones
        (type STRING)
        (create-accessor read-write))
    (slot Complejidad
        (type INTEGER)
        (create-accessor read-write))
    (slot Relevancia
        (type INTEGER)
        (create-accessor read-write))
    (slot Ubicado_en    ;Relacion con Sala
        (type INSTANCE)
        (create-accessor read-write))
)

;--------------------------------------------------;
;--------------------- PINTOR ---------------------;
;--------------------------------------------------;

(defclass Pintor
    (is-a USER)
    (role concrete)
    (pattern-match reactive)
    (slot Nombre
        (type STRING)
        (create-accessor read-write))
    (slot Nacionalidad
        (type STRING)
        (create-accessor read-write))
    (slot Estilo
        (type STRING)
        (create-accessor read-write))
    (slot Epoca
        (type STRING)
        (create-accessor read-write))
    (multislot Ha_pintado   ;Relacion con Cuadro
        (type INSTANCE)
        (create-accessor read-write))
)

;--------------------------------------------------;
;-------------------- VISITANTE -------------------;
;--------------------------------------------------;

(defclass Visitantes
    (is-a USER)
    (role concrete)
    (pattern-match reactive)
    (slot Nombre
        (type STRING)
        (create-accessor read-write))
    (slot TipoDeVisitante
        (type STRING)
        (create-accessor read-write))
    (slot DiasDeVisita      ;a lo mejor se mueve a otra clase
        (type INTEGER)
        (create-accessor read-write))
    (slot DuracionVisita    ;a lo mejor se mueve a otra clase
        (type INTEGER)
        (create-accessor read-write))
    (slot Conocimiento
        (type INTEGER)
        (create-accessor read-write))
    (multislot Preferencias
        (type STRING)
        (create-accessor read-write))
)

;--------------------------------------------------;
;------------------- INSTANCIAS -------------------;
;--------------------------------------------------;

(definstances Salas
    ([SalaRenacimiento] of Sala
        (Nombre "Sala 1: Renacimiento"))

    ([SalaBarroco] of Sala
        (Nombre "Sala 2: Barroco"))
    
    ([SalaRococo] of Sala
        (Nombre "Sala 3: Rococo"))

    ([SalaNeoclasicismo] of Sala
        (Nombre "Sala 4: Neoclasicismo"))

    ([SalaRomanticismo] of Sala
        (Nombre "Sala 5: Romanticismo"))

    ([SalaImpresionismo] of Sala
        (Nombre "Sala 6: Impresionismo"))

    ([SalaPosimpresionismo] of Sala
        (Nombre "Sala 7: Posimpresionismo"))

    ([SalaVictoriana] of Sala
        (Nombre "Sala 8: Victoriana"))
)

(definstances Cuadros
    ([Cuadro1] of Cuadro
        (Titulo "Retrato de un hombre con turbante rojo")
        (AnyCreacion 1433)
        (Pintado_por [Pintor28])
        (Epoca "Renacimiento")
        (Estilo "Primitivismo flamenco")
        (Tematica "Retrato masculino")
        (Dimensiones "25 x 19")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro2] of Cuadro
        (Titulo "El matrimonio Arnolfini")
        (AnyCreacion 1434)
        (Pintado_por [Pintor28])
        (Epoca "Renacimiento")
        (Estilo "Primitivismo flamenco")
        (Tematica "Retrato doble")
        (Dimensiones "82 x 60")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro3] of Cuadro
        (Titulo "La flagelacion de Cristo")
        (AnyCreacion 1460)
        (Pintado_por [Pintor43])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena religiosa")
        (Dimensiones "58 x 81")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro4] of Cuadro
        (Titulo "La Primavera")
        (AnyCreacion 1481)
        (Pintado_por [Pintor49])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena mitologica")
        (Dimensiones "203 x 314")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro5] of Cuadro
        (Titulo "Virgen de las Rocas")
        (AnyCreacion 1483)
        (Pintado_por [Pintor34])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena religiosa")
        (Dimensiones "199 x 122")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro6] of Cuadro
        (Titulo "Venus y Marte")
        (AnyCreacion 1483)
        (Pintado_por [Pintor49])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena mitologica")
        (Dimensiones "69 x 173")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro7] of Cuadro
        (Titulo "El nacimiento de Venus")
        (AnyCreacion 1485)
        (Pintado_por [Pintor49])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena mitologica")
        (Dimensiones "172 x 278")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro8] of Cuadro
        (Titulo "El jardin de las delicias")
        (AnyCreacion 1495)
        (Pintado_por [Pintor22])
        (Epoca "Renacimiento")
        (Estilo "Primitivismo flamenco")
        (Tematica "Escena alegorica")
        (Dimensiones "220 x 389")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro9] of Cuadro
        (Titulo "La ultima cena")
        (AnyCreacion 1496)
        (Pintado_por [Pintor34])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena biblica")
        (Dimensiones "460 x 880")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro10] of Cuadro
        (Titulo "Sagrado Semblante")
        (AnyCreacion 1500)
        (Pintado_por [Pintor1])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena religiosa")
        (Dimensiones "37 x 28")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro11] of Cuadro
        (Titulo "Mona Lisa")
        (AnyCreacion 1503)
        (Pintado_por [Pintor34])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Retrato femenino")
        (Dimensiones "77 x 53")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro12] of Cuadro
        (Titulo "La escuela de Atenas")
        (AnyCreacion 1510)
        (Pintado_por [Pintor47])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena historica")
        (Dimensiones "500 x 770")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro13] of Cuadro
        (Titulo "Creacion de los astros y las plantas")
        (AnyCreacion 1511)
        (Pintado_por [Pintor38])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena biblica")
        (Dimensiones "280 x 570")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro14] of Cuadro
        (Titulo "La creacion de Adan")
        (AnyCreacion 1512)
        (Pintado_por [Pintor38])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena biblica")
        (Dimensiones "280 x 570")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro15] of Cuadro
        (Titulo "Expulsion del Paraiso")
        (AnyCreacion 1512)
        (Pintado_por [Pintor38])
        (Epoca "Renacimiento")
        (Estilo "Cinquecento")
        (Tematica "Escena biblica")
        (Dimensiones "280 x 570")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro16] of Cuadro
        (Titulo "La Asuncion de la Virgen")
        (AnyCreacion 1517)
        (Pintado_por [Pintor52])
        (Epoca "Renacimiento")
        (Estilo "Escuela Veneciana")
        (Tematica "Escena religiosa")
        (Dimensiones "690 x 360")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro17] of Cuadro
        (Titulo "Epifania")
        (AnyCreacion 1520)
        (Pintado_por [Pintor23])
        (Epoca "Renacimiento")
        (Estilo "Renacimiento")
        (Tematica "Escena religiosa")
        (Dimensiones "89 x 184")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro18] of Cuadro
        (Titulo "La Torre de Babel")
        (AnyCreacion 1563)
        (Pintado_por [Pintor46])
        (Epoca "Renacimiento")
        (Estilo "Primitivismo flamenco")
        (Tematica "Escena biblica")
        (Dimensiones "114 x 155")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro19] of Cuadro
        (Titulo "Baco adolescente")
        (AnyCreacion 1593)
        (Pintado_por [Pintor6])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "95 x 85")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro20] of Cuadro
        (Titulo "Apolo tocando el laud")
        (AnyCreacion 1596)
        (Pintado_por [Pintor6])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena musical")
        (Dimensiones "94 x 119")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro21] of Cuadro
        (Titulo "Leda y el cisne")
        (AnyCreacion 1600)
        (Pintado_por [Pintor42])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "64 x 80")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro22] of Cuadro
        (Titulo "La incredulidad de Santo Tomas")
        (AnyCreacion 1602)
        (Pintado_por [Pintor6])
        (Epoca "Barroco")
        (Estilo "Tenebrismo, Barroco")
        (Tematica "Escena religiosa")
        (Dimensiones "107 x 146")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro23] of Cuadro
        (Titulo "Cristo cargando la cruz")
        (AnyCreacion 1603)
        (Pintado_por [Pintor11])
        (Epoca "Renacimiento")
        (Estilo "Manierismo")
        (Tematica "Escena biblica")
        (Dimensiones "108 x 78")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRenacimiento])
    )
    ([Cuadro24] of Cuadro
        (Titulo "David con la cabeza de Goliat")
        (AnyCreacion 1610)
        (Pintado_por [Pintor6])
        (Epoca "Barroco")
        (Estilo "Tenebrismo, Barroco")
        (Tematica "Escena biblica")
        (Dimensiones "125 x 100")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro25] of Cuadro
        (Titulo "Judith decapitando a Holofern")
        (AnyCreacion 1613)
        (Pintado_por [Pintor3])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena biblica")
        (Dimensiones "158 x 125")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro26] of Cuadro
        (Titulo "Dos satiros")
        (AnyCreacion 1619)
        (Pintado_por [Pintor42])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "76 x 61")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro27] of Cuadro
        (Titulo "Retrato de Gongora")
        (AnyCreacion 1622)
        (Pintado_por [Pintor9])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Retrato masculino")
        (Dimensiones "59 x 46")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro28] of Cuadro
        (Titulo "La fragua de Vulcano")
        (AnyCreacion 1630)
        (Pintado_por [Pintor9])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "223 x 290")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro29] of Cuadro
        (Titulo "La rendicion de Breda")
        (AnyCreacion 1635)
        (Pintado_por [Pintor9])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena historica")
        (Dimensiones "307 x 367")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro30] of Cuadro
        (Titulo "Paisaje con Ruinas")
        (AnyCreacion 1635)
        (Pintado_por [Pintor7])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Paisaje rural")
        (Dimensiones "100 x 135")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro31] of Cuadro
        (Titulo "Las Lanzas (La Rendicion de Breda)")
        (AnyCreacion 1635)
        (Pintado_por [Pintor9])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena historica")
        (Dimensiones "307 x 367")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro32] of Cuadro
        (Titulo "San Miguel")
        (AnyCreacion 1636)
        (Pintado_por [Pintor20])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena religiosa")
        (Dimensiones "293 x 202")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro33] of Cuadro
        (Titulo "Las Bodas de Tetis y Peleo")
        (AnyCreacion 1637)
        (Pintado_por [Pintor25])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "181 x 288")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro34] of Cuadro
        (Titulo "Et in Arcadia ego")
        (AnyCreacion 1638)
        (Pintado_por [Pintor39])
        (Epoca "Barroco")
        (Estilo "Clasicismo frances")
        (Tematica "Escena alegorica")
        (Dimensiones "87 x 120")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro35] of Cuadro
        (Titulo "El juicio de Paris")
        (AnyCreacion 1638)
        (Pintado_por [Pintor42])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "99 x 381")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro36] of Cuadro
        (Titulo "Las tres Gracias")
        (AnyCreacion 1639)
        (Pintado_por [Pintor42])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena mitologica")
        (Dimensiones "221 x 181")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro37] of Cuadro
        (Titulo "La ronda de noche")
        (AnyCreacion 1642)
        (Pintado_por [Pintor48])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Retrato grupal")
        (Dimensiones "379 x 453")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro38] of Cuadro
        (Titulo "Diogenes y la linterna")
        (AnyCreacion 1645)
        (Pintado_por [Pintor25])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena filosofica")
        (Dimensiones "233 x 349")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro39] of Cuadro
        (Titulo "El joven mendigo")
        (AnyCreacion 1650)
        (Pintado_por [Pintor5])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Escena de genero")
        (Dimensiones "134 x 100")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro40] of Cuadro
        (Titulo "Las meninas")
        (AnyCreacion 1656)
        (Pintado_por [Pintor9])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Retrato grupal")
        (Dimensiones "318 x 276")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro41] of Cuadro
        (Titulo "La joven de la perla")
        (AnyCreacion 1665)
        (Pintado_por [Pintor31])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Retrato femenino")
        (Dimensiones "44 x 39")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro42] of Cuadro
        (Titulo "Retrato de Luis XIV")
        (AnyCreacion 1701)
        (Pintado_por [Pintor24])
        (Epoca "Barroco")
        (Estilo "Barroco")
        (Tematica "Retrato real")
        (Dimensiones "277 x 194")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaBarroco])
    )
    ([Cuadro43] of Cuadro
        (Titulo "El Bucintoro")
        (AnyCreacion 1729)
        (Pintado_por [Pintor19])
        (Epoca "Rococo")
        (Estilo "Vedutismo, Rococo")
        (Tematica "Paisaje urbano")
        (Dimensiones "99 x 146")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro44] of Cuadro
        (Titulo "Entrada al Gran Canal")
        (AnyCreacion 1730)
        (Pintado_por [Pintor19])
        (Epoca "Rococo")
        (Estilo "Vedutismo, Rococo")
        (Tematica "Paisaje urbano")
        (Dimensiones "50 x 73")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro45] of Cuadro
        (Titulo "Caronte atravesando las sombras de la laguna Estigia")
        (AnyCreacion 1740)
        (Pintado_por [Pintor45])
        (Epoca "Rococo")
        (Estilo "Vedutismo")
        (Tematica "Escena mitologica")
        (Dimensiones "135 x 83")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro46] of Cuadro
        (Titulo "La familia de Felipe V")
        (AnyCreacion 1743)
        (Pintado_por [Pintor35])
        (Epoca "Rococo")
        (Estilo "Rococo")
        (Tematica "Retrato real")
        (Dimensiones "408 x 520")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro47] of Cuadro
        (Titulo "El senor y la senora Andrews")
        (AnyCreacion 1750)
        (Pintado_por [Pintor51])
        (Epoca "Rococo")
        (Estilo "Rococo")
        (Tematica "Retrato doble")
        (Dimensiones "69 x 119")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro48] of Cuadro
        (Titulo "Los sirvientes del pintor")
        (AnyCreacion 1755)
        (Pintado_por [Pintor54])
        (Epoca "Rococo")
        (Estilo "Rococo")
        (Tematica "Retrato grupal")
        (Dimensiones "63 x 75")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro49] of Cuadro
        (Titulo "El columpio")
        (AnyCreacion 1767)
        (Pintado_por [Pintor30])
        (Epoca "Rococo")
        (Estilo "Rococo")
        (Tematica "Escena galante")
        (Dimensiones "81 x 64")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro50] of Cuadro
        (Titulo "La cerradura")
        (AnyCreacion 1768)
        (Pintado_por [Pintor30])
        (Epoca "Rococo")
        (Estilo "Rococo")
        (Tematica "Escena intima")
        (Dimensiones "73 x 93")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRococo])
    )
    ([Cuadro51] of Cuadro
        (Titulo "Retrato de Madame Francois Buron")
        (AnyCreacion 1769)
        (Pintado_por [Pintor26])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo frances")
        (Tematica "Retrato femenino")
        (Dimensiones "63 x 52")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro52] of Cuadro
        (Titulo "La pesadilla")
        (AnyCreacion 1781)
        (Pintado_por [Pintor21])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Escena dramatica")
        (Dimensiones "101 x 127")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro53] of Cuadro
        (Titulo "El juramento de los Horacios")
        (AnyCreacion 1784)
        (Pintado_por [Pintor26])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo")
        (Tematica "Escena historica")
        (Dimensiones "330 x 425")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro54] of Cuadro
        (Titulo "La muerte de Socrates")
        (AnyCreacion 1787)
        (Pintado_por [Pintor26])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo frances")
        (Tematica "Escena historica")
        (Dimensiones "129 x 196")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro55] of Cuadro
        (Titulo "El aquelarre")
        (AnyCreacion 1789)
        (Pintado_por [Pintor14])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo, Pintura oscura")
        (Tematica "Escena mitologica")
        (Dimensiones "43 x 30")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro56] of Cuadro
        (Titulo "La banista")
        (AnyCreacion 1792)
        (Pintado_por [Pintor12])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasico")
        (Tematica "Retrato femenino")
        (Dimensiones "73 x 55")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro57] of Cuadro
        (Titulo "La Duquesa de Alba de negro")
        (AnyCreacion 1797)
        (Pintado_por [Pintor14])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Retrato individual")
        (Dimensiones "210 x 150")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro58] of Cuadro
        (Titulo "La maja desnuda")
        (AnyCreacion 1797)
        (Pintado_por [Pintor14])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo")
        (Tematica "Retrato femenino")
        (Dimensiones "97 x 190")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro59] of Cuadro
        (Titulo "Napoleon cruzando los Alpes")
        (AnyCreacion 1801)
        (Pintado_por [Pintor26])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo")
        (Tematica "Retrato individual")
        (Dimensiones "261 x 221")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro60] of Cuadro
        (Titulo "Retrato de Madame Duvaucey")
        (AnyCreacion 1807)
        (Pintado_por [Pintor29])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo frances")
        (Tematica "Retrato femenino")
        (Dimensiones "108 x 87")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro61] of Cuadro
        (Titulo "Lazarillo de Tormes")
        (AnyCreacion 1810)
        (Pintado_por [Pintor14])
        (Epoca "Romanticismo")
        (Estilo "Pinturas negras")
        (Tematica "Escena literaria")
        (Dimensiones "80 x 65")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro62] of Cuadro
        (Titulo "Los fusilamientos del 3 de mayo")
        (AnyCreacion 1814)
        (Pintado_por [Pintor14])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Escena historica")
        (Dimensiones "268 x 347")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro63] of Cuadro
        (Titulo "La balsa de la Medusa")
        (AnyCreacion 1818)
        (Pintado_por [Pintor50])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Escena mitologica")
        (Dimensiones "491 x 716")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro64] of Cuadro
        (Titulo "La colera de Aquiles")
        (AnyCreacion 1819)
        (Pintado_por [Pintor26])
        (Epoca "Neoclasicismo")
        (Estilo "Neoclasicismo")
        (Tematica "Escena mitologica")
        (Dimensiones "105 x 145")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaNeoclasicismo])
    )
    ([Cuadro65] of Cuadro
        (Titulo "Saturno devorando a su hijo")
        (AnyCreacion 1821)
        (Pintado_por [Pintor14])
        (Epoca "Romanticismo")
        (Estilo "Pinturas Negras, Romanticismo")
        (Tematica "Escena mitologica")
        (Dimensiones "143 x 81")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro66] of Cuadro
        (Titulo "La ejecucion de Lady Jane Grey")
        (AnyCreacion 1833)
        (Pintado_por [Pintor41])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Escena historica")
        (Dimensiones "246 x 297")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro67] of Cuadro
        (Titulo "El angel caido")
        (AnyCreacion 1847)
        (Pintado_por [Pintor2])
        (Epoca "Romanticismo")
        (Estilo "Academico, con influencias romanticas")
        (Tematica "Escena biblica")
        (Dimensiones "105 x 138")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro68] of Cuadro
        (Titulo "Dante y Virgilio en el infierno")
        (AnyCreacion 1850)
        (Pintado_por [Pintor55])
        (Epoca "Romanticismo")
        (Estilo "Academicismo frances")
        (Tematica "Escena literaria")
        (Dimensiones "281 x 225")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro69] of Cuadro
        (Titulo "Ofelia")
        (AnyCreacion 1852)
        (Pintado_por [Pintor32])
        (Epoca "Victoriana")
        (Estilo "Prerrafaelismo")
        (Tematica "Escena literaria")
        (Dimensiones "76 x 111")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaVictoriana])
    )
    ([Cuadro70] of Cuadro
        (Titulo "La chica ciega")
        (AnyCreacion 1856)
        (Pintado_por [Pintor32])
        (Epoca "Victoriana")
        (Estilo "Pre-Rafaelismo")
        (Tematica "Escena dramatica")
        (Dimensiones "81 x 61")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaVictoriana])
    )
    ([Cuadro71] of Cuadro
        (Titulo "El beso")
        (AnyCreacion 1859)
        (Pintado_por [Pintor13])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Escena romantica")
        (Dimensiones "112 x 88")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro72] of Cuadro
        (Titulo " El bufon Stanczyk")
        (AnyCreacion 1862)
        (Pintado_por [Pintor27])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Retrato individual")
        (Dimensiones "88 x 120")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro73] of Cuadro
        (Titulo "La prometida vacilante")
        (AnyCreacion 1866)
        (Pintado_por [Pintor4])
        (Epoca "Impresionismo")
        (Estilo "Academicismo")
        (Tematica "Retrato femenino")
        (Dimensiones "65 x 54")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaImpresionismo])
    )
    ([Cuadro74] of Cuadro
        (Titulo "La Vicaria")
        (AnyCreacion 1870)
        (Pintado_por [Pintor36])
        (Epoca "Romanticismo")
        (Estilo "Orientalismo y costumbrismo")
        (Tematica "Escena costumbrista")
        (Dimensiones "60 x 93")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro75] of Cuadro
        (Titulo "Impresion, sol naciente")
        (AnyCreacion 1872)
        (Pintado_por [Pintor8])
        (Epoca "Impresionismo")
        (Estilo "Impresionismo")
        (Tematica "Paisaje urbano")
        (Dimensiones "48 x 63")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaImpresionismo])
    )
    ([Cuadro76] of Cuadro
        (Titulo "Thor lucha contra los gigantes")
        (AnyCreacion 1872)
        (Pintado_por [Pintor37])
        (Epoca "Romanticismo")
        (Estilo "Romanticismo")
        (Tematica "Escena mitologica")
        (Dimensiones "484 x 333")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro77] of Cuadro
        (Titulo "Primavera")
        (AnyCreacion 1873)
        (Pintado_por [Pintor44])
        (Epoca "Romanticismo")
        (Estilo "Academicismo frances")
        (Tematica "Escena romantica")
        (Dimensiones "213 x 127")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro78] of Cuadro
        (Titulo "Mujer con sombrilla")
        (AnyCreacion 1875)
        (Pintado_por [Pintor8])
        (Epoca "Impresionismo")
        (Estilo "Impresionismo")
        (Tematica "Retrato familiar")
        (Dimensiones "81 x 100")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaImpresionismo])
    )
    ([Cuadro79] of Cuadro
        (Titulo "Romeo y Julieta en el balcon")
        (AnyCreacion 1884)
        (Pintado_por [Pintor16])
        (Epoca "Romanticismo")
        (Estilo "Prerrafaelismo y academicismo")
        (Tematica "Escena literaria")
        (Dimensiones "145 x 109")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro80] of Cuadro
        (Titulo "Caballeria")
        (AnyCreacion 1885)
        (Pintado_por [Pintor16])
        (Epoca "Romanticismo")
        (Estilo "Prerrafaelismo y academicismo")
        (Tematica "Escena romantica")
        (Dimensiones "157 x 116")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro81] of Cuadro
        (Titulo "Domingo en la Grande Jatte")
        (AnyCreacion 1886)
        (Pintado_por [Pintor18])
        (Epoca "Posimpresionismo")
        (Estilo "Puntillismo")
        (Tematica "Escena costumbrista")
        (Dimensiones "207,5 x 308")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro82] of Cuadro
        (Titulo "Las mujeres de Amfissa")
        (AnyCreacion 1887)
        (Pintado_por [Pintor33])
        (Epoca "Romanticismo")
        (Estilo "Pintura academica con tematica clasica")
        (Tematica "Escena historica")
        (Dimensiones "122 x 184")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaRomanticismo])
    )
    ([Cuadro83] of Cuadro
        (Titulo "Campo de trigo al atardecer")
        (AnyCreacion 1888)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Paisaje rural")
        (Dimensiones "73 x 92")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro84] of Cuadro
        (Titulo "Los girasoles")
        (AnyCreacion 1888)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Naturaleza")
        (Dimensiones "92 x 73")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro85] of Cuadro
        (Titulo "La noche estrellada")
        (AnyCreacion 1889)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Paisaje rural")
        (Dimensiones "73 x 92")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro86] of Cuadro
        (Titulo "Autorretrato")
        (AnyCreacion 1889)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Retrato individual")
        (Dimensiones "65 x 55")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro87] of Cuadro
        (Titulo "Campo de trigo con cipreses")
        (AnyCreacion 1889)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Paisaje rural")
        (Dimensiones "73 x 93")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro88] of Cuadro
        (Titulo "Olivos")
        (AnyCreacion 1889)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Paisaje rural")
        (Dimensiones "73 x 93")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro89] of Cuadro
        (Titulo "Almendro en flor")
        (AnyCreacion 1890)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Naturaleza")
        (Dimensiones "73 x 92")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro90] of Cuadro
        (Titulo "Descanso al mediodia")
        (AnyCreacion 1890)
        (Pintado_por [Pintor53])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Escena costumbrista")
        (Dimensiones "73 x 92")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro91] of Cuadro
        (Titulo "Sol ardiente de junio")
        (AnyCreacion 1895)
        (Pintado_por [Pintor17])
        (Epoca "Victoriana")
        (Estilo "Academico")
        (Tematica "Escena intima")
        (Dimensiones "120 x 120")
        (Complejidad 0)
        (Relevancia 4)
        (Ubicado_en [SalaVictoriana])
    )
    ([Cuadro92] of Cuadro
        (Titulo "El hombre con el craneo")
        (AnyCreacion 1897)
        (Pintado_por [Pintor40])
        (Epoca "Posimpresionismo")
        (Estilo "Posimpresionismo")
        (Tematica "Escena filosofica")
        (Dimensiones "72 x 91")
        (Complejidad 0)
        (Relevancia 2)
        (Ubicado_en [SalaPosimpresionismo])
    )
    ([Cuadro93] of Cuadro
        (Titulo "El puente japones")
        (AnyCreacion 1899)
        (Pintado_por [Pintor8])
        (Epoca "Impresionismo")
        (Estilo "Impresionismo")
        (Tematica "Paisaje rural")
        (Dimensiones "82 x 93")
        (Complejidad 0)
        (Relevancia 5)
        (Ubicado_en [SalaImpresionismo])
    )
    ([Cuadro94] of Cuadro
        (Titulo "El abrazo")
        (AnyCreacion 1901)
        (Pintado_por [Pintor10])
        (Epoca "Victoriana")
        (Estilo "Realismo academico")
        (Tematica "Escena romantica")
        (Dimensiones "182 x 108")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaVictoriana])
    )
    ([Cuadro95] of Cuadro
        (Titulo "La Bella Dame sans Merci")
        (AnyCreacion 1902)
        (Pintado_por [Pintor16])
        (Epoca "Victoriana")
        (Estilo "Pre-Rafaelista/Simbolista")
        (Tematica "Escena dramatica")
        (Dimensiones "137,2 x 188")
        (Complejidad 0)
        (Relevancia 3)
        (Ubicado_en [SalaVictoriana])
    )
    ([Cuadro96] of Cuadro
        (Titulo "Vanidad")
        (AnyCreacion 1907)
        (Pintado_por [Pintor15])
        (Epoca "Romanticismo")
        (Estilo "Pre-Rafaelismo")
        (Tematica "Retrato femenino")
        (Dimensiones "57 x 38")
        (Complejidad 0)
        (Relevancia 1)
        (Ubicado_en [SalaRomanticismo])
    )
)

(definstances Pintores
    ([Pintor1] of Pintor
        (Nombre "Aelbrecht Bouts")
        (Nacionalidad Flamenco)
        (Estilo "Primitivos Flamencos")
        (Epoca "1475-1549")
        (Ha_pintado [Cuadro10])
    )
    ([Pintor2] of Pintor
        (Nombre "Alexandre Cabanel")
        (Nacionalidad Frances)
        (Estilo "Academicismo")
        (Epoca "1840-1889")
        (Ha_pintado [Cuadro67])
    )
    ([Pintor3] of Pintor
        (Nombre "Artemisia Gentileschi")
        (Nacionalidad Italiana)
        (Estilo "Barroco")
        (Epoca "1610-1656")
        (Ha_pintado [Cuadro25])
    )
    ([Pintor4] of Pintor
        (Nombre "Auguste Toulmouche")
        (Nacionalidad Frances)
        (Estilo "Realismo")
        (Epoca "1848-1890")
        (Ha_pintado [Cuadro73])
    )
    ([Pintor5] of Pintor
        (Nombre "Bartolome Esteban Murillo")
        (Nacionalidad Español)
        (Estilo "Barroco")
        (Epoca "1645-1682")
        (Ha_pintado [Cuadro39])
    )
    ([Pintor6] of Pintor
        (Nombre "Caravaggio")
        (Nacionalidad Italiano)
        (Estilo "Barroco")
        (Epoca "1592-1610")
        (Ha_pintado [Cuadro19] [Cuadro20] [Cuadro22] [Cuadro24])
    )
    ([Pintor7] of Pintor
        (Nombre "Claude Lorrain")
        (Nacionalidad Frances)
        (Estilo "Barroco")
        (Epoca "1627-1682")
        (Ha_pintado [Cuadro30])
    )
    ([Pintor8] of Pintor
        (Nombre "Claude Monet")
        (Nacionalidad Frances)
        (Estilo "Impresionismo")
        (Epoca "1858-1926")
        (Ha_pintado [Cuadro75] [Cuadro78] [Cuadro93])
    )
    ([Pintor9] of Pintor
        (Nombre "Diego Velazquez")
        (Nacionalidad Español)
        (Estilo "Barroco")
        (Epoca "1617-1660")
        (Ha_pintado [Cuadro27] [Cuadro28] [Cuadro29] [Cuadro31] [Cuadro40])
    )
    ([Pintor10] of Pintor
        (Nombre "Edmund Blair Leighton")
        (Nacionalidad Britanico)
        (Estilo "Romanticismo")
        (Epoca "1878-1920")
        (Ha_pintado [Cuadro94])
    )
    ([Pintor11] of Pintor
        (Nombre "El Greco")
        (Nacionalidad Griego)
        (Estilo "Manierismo")
        (Epoca "1563-1614")
        (Ha_pintado [Cuadro23])
    )
    ([Pintor12] of Pintor
        (Nombre "Elisabeth Vigee-LeBrun")
        (Nacionalidad Francesa)
        (Estilo "Rococo")
        (Epoca "1774-1827")
        (Ha_pintado [Cuadro56])
    )
    ([Pintor13] of Pintor
        (Nombre "Francesco Hayez")
        (Nacionalidad Italiano)
        (Estilo "Romanticismo")
        (Epoca "1813-1882")
        (Ha_pintado [Cuadro71])
    )
    ([Pintor14] of Pintor
        (Nombre "Francisco de Goya")
        (Nacionalidad Español)
        (Estilo "Romanticismo")
        (Epoca "1771-1828")
        (Ha_pintado [Cuadro55] [Cuadro57] [Cuadro58] [Cuadro61] [Cuadro62] [Cuadro65])
    )
    ([Pintor15] of Pintor
        (Nombre "Frank Cadogan Cowper")
        (Nacionalidad Britanico)
        (Estilo "Prerrafaelismo")
        (Epoca "1899-1958")
        (Ha_pintado [Cuadro96])
    )
    ([Pintor16] of Pintor
        (Nombre "Frank Dicksee")
        (Nacionalidad Britanico)
        (Estilo "Prerrafaelismo")
        (Epoca "1877-1928")
        (Ha_pintado [Cuadro79] [Cuadro80] [Cuadro95])
    )
    ([Pintor17] of Pintor
        (Nombre "Frederic Leighton")
        (Nacionalidad Britanico)
        (Estilo "Academicismo")
        (Epoca "1855-1896")
        (Ha_pintado [Cuadro91])
    )
    ([Pintor18] of Pintor
        (Nombre "Georges Seurat")
        (Nacionalidad Frances)
        (Estilo "Puntillismo")
        (Epoca "1880-1891")
        (Ha_pintado [Cuadro81])
    )
    ([Pintor19] of Pintor
        (Nombre "Giovanni Antonio Canal (Canaletto)")
        (Nacionalidad Italiano)
        (Estilo "Vedutismo")
        (Epoca "1719-1768")
        (Ha_pintado [Cuadro43] [Cuadro44])
    )
    ([Pintor20] of Pintor
        (Nombre "Guido Reni")
        (Nacionalidad Italiano)
        (Estilo "Barroco")
        (Epoca "1595-1642")
        (Ha_pintado [Cuadro32])
    )
    ([Pintor21] of Pintor
        (Nombre "Henry Fuseli")
        (Nacionalidad Suizo)
        (Estilo "Romanticismo")
        (Epoca "1770-1825")
        (Ha_pintado [Cuadro52])
    )
    ([Pintor22] of Pintor
        (Nombre "Hieronymus Bosch (El Bosco)")
        (Nacionalidad Neerlandes)
        (Estilo "Renacimiento del Norte")
        (Epoca "1470-1516")
        (Ha_pintado [Cuadro8])
    )
    ([Pintor23] of Pintor
        (Nombre "Hugo van der Goes")
        (Nacionalidad Flamenco)
        (Estilo "Primitivos Flamencos")
        (Epoca "1467-1482")
        (Ha_pintado [Cuadro17])
    )
    ([Pintor24] of Pintor
        (Nombre "Hyacinthe Rigaud")
        (Nacionalidad Frances)
        (Estilo "Barroco")
        (Epoca "1680-1743")
        (Ha_pintado [Cuadro42])
    )
    ([Pintor25] of Pintor
        (Nombre "Jacob Jordaens")
        (Nacionalidad Flamenco)
        (Estilo "Barroco")
        (Epoca "1615-1678")
        (Ha_pintado [Cuadro33] [Cuadro38])
    )
    ([Pintor26] of Pintor
        (Nombre "Jacques-Louis David")
        (Nacionalidad Frances)
        (Estilo "Neoclasicismo")
        (Epoca "1770-1825")
        (Ha_pintado [Cuadro51] [Cuadro53] [Cuadro54] [Cuadro59] [Cuadro64])
    )
    ([Pintor27] of Pintor
        (Nombre "Jan Matejko")
        (Nacionalidad Polaco)
        (Estilo "Romanticismo")
        (Epoca "1852-1893")
        (Ha_pintado [Cuadro72])
    )
    ([Pintor28] of Pintor
        (Nombre "Jan van Eyck")
        (Nacionalidad Flamenco)
        (Estilo "Primitivos Flamencos")
        (Epoca "1422-1441")
        (Ha_pintado [Cuadro1] [Cuadro2])
    )
    ([Pintor29] of Pintor
        (Nombre "Jean-Auguste-Dominique Ingres")
        (Nacionalidad Frances)
        (Estilo "Neoclasicismo")
        (Epoca "1800-1867")
        (Ha_pintado [Cuadro60])
    )
    ([Pintor30] of Pintor
        (Nombre "Jean-Honore Fragonard")
        (Nacionalidad Frances)
        (Estilo "Rococo")
        (Epoca "1755-1806")
        (Ha_pintado [Cuadro49] [Cuadro50])
    )
    ([Pintor31] of Pintor
        (Nombre "Johannes Vermeer")
        (Nacionalidad Neerlandes)
        (Estilo "Barroco")
        (Epoca "1653-1675")
        (Ha_pintado [Cuadro41])
    )
    ([Pintor32] of Pintor
        (Nombre "John Everett Millais")
        (Nacionalidad Britanico)
        (Estilo "Prerrafaelismo")
        (Epoca "1848-1896")
        (Ha_pintado [Cuadro69] [Cuadro70])
    )
    ([Pintor33] of Pintor
        (Nombre "Lawrence Alma-Tadema")
        (Nacionalidad Britanico)
        (Estilo "Academicismo")
        (Epoca "1852-1912")
        (Ha_pintado [Cuadro82])
    )
    ([Pintor34] of Pintor
        (Nombre "Leonardo da Vinci")
        (Nacionalidad Italiano)
        (Estilo "Renacimiento")
        (Epoca "1472-1519")
        (Ha_pintado [Cuadro5] [Cuadro9] [Cuadro11])
    )
    ([Pintor35] of Pintor
        (Nombre "Louis-Michel Van Loo")
        (Nacionalidad Frances)
        (Estilo "Rococo")
        (Epoca "1723-1771")
        (Ha_pintado [Cuadro46])
    )
    ([Pintor36] of Pintor
        (Nombre "Mariano Fortuny")
        (Nacionalidad Español)
        (Estilo "Realismo, Orientalismo")
        (Epoca "1857-1874")
        (Ha_pintado [Cuadro74])
    )
    ([Pintor37] of Pintor
        (Nombre "Marten Eskil Winge")
        (Nacionalidad Sueco)
        (Estilo "Romanticismo")
        (Epoca "1847-1896")
        (Ha_pintado [Cuadro76])
    )
    ([Pintor38] of Pintor
        (Nombre "Miguel Angel Buonarroti")
        (Nacionalidad Italiano)
        (Estilo "Renacimiento")
        (Epoca "1490-1564")
        (Ha_pintado [Cuadro13] [Cuadro14] [Cuadro15])
    )
    ([Pintor39] of Pintor
        (Nombre "Nicolas Poussin")
        (Nacionalidad Frances)
        (Estilo "Clasicismo")
        (Epoca "1610-1665")
        (Ha_pintado [Cuadro34])
    )
    ([Pintor40] of Pintor
        (Nombre "Paul Cezanne")
        (Nacionalidad Frances)
        (Estilo "Postimpresionismo")
        (Epoca "1860-1906")
        (Ha_pintado [Cuadro92])
    )
    ([Pintor41] of Pintor
        (Nombre "Paul Delaroche")
        (Nacionalidad Frances)
        (Estilo "Academicismo")
        (Epoca "1815-1856")
        (Ha_pintado [Cuadro66])
    )
    ([Pintor42] of Pintor
        (Nombre "Peter Paul Rubens")
        (Nacionalidad Flamenco)
        (Estilo "Barroco")
        (Epoca "1598-1640")
        (Ha_pintado [Cuadro21] [Cuadro26] [Cuadro35] [Cuadro36])
    )
    ([Pintor43] of Pintor
        (Nombre "Piero della Francesca")
        (Nacionalidad Italiano)
        (Estilo "Renacimiento")
        (Epoca "1432-1492")
        (Ha_pintado [Cuadro3])
    )
    ([Pintor44] of Pintor
        (Nombre "Pierre Auguste Cot")
        (Nacionalidad Frances)
        (Estilo "Academicismo")
        (Epoca "1860-1883")
        (Ha_pintado [Cuadro77])
    )
    ([Pintor45] of Pintor
        (Nombre "Pierre Subleyras")
        (Nacionalidad Frances)
        (Estilo "Rococo")
        (Epoca "1727-1749")
        (Ha_pintado [Cuadro45])
    )
    ([Pintor46] of Pintor
        (Nombre "Pieter Bruegel el Viejo")
        (Nacionalidad Flamenco)
        (Estilo "Renacimiento")
        (Epoca "1551-1569")
        (Ha_pintado [Cuadro18])
    )
    ([Pintor47] of Pintor
        (Nombre "Rafael Sanzio")
        (Nacionalidad Italiano)
        (Estilo "Renacimiento")
        (Epoca "1500-1520")
        (Ha_pintado [Cuadro12])
    )
    ([Pintor48] of Pintor
        (Nombre "Rembrandt van Rijn")
        (Nacionalidad Neerlandes)
        (Estilo "Barroco")
        (Epoca "1625-1669")
        (Ha_pintado [Cuadro37])
    )
    ([Pintor49] of Pintor
        (Nombre "Sandro Botticelli")
        (Nacionalidad Italiano)
        (Estilo "Renacimiento")
        (Epoca "1470-1500")
        (Ha_pintado [Cuadro4] [Cuadro6] [Cuadro7])
    )
    ([Pintor50] of Pintor
        (Nombre "Theodore Gericault")
        (Nacionalidad Frances)
        (Estilo "Romanticismo")
        (Epoca "1812-1824")
        (Ha_pintado [Cuadro63])
    )
    ([Pintor51] of Pintor
        (Nombre "Thomas Gainsborough")
        (Nacionalidad Britanico)
        (Estilo "Rococo")
        (Epoca "1745-1788")
        (Ha_pintado [Cuadro47])
    )
    ([Pintor52] of Pintor
        (Nombre "Tiziano Vecellio")
        (Nacionalidad Italiano)
        (Estilo "Renacimiento")
        (Epoca "1506-1576")
        (Ha_pintado [Cuadro16])
    )
    ([Pintor53] of Pintor
        (Nombre "Vincent van Gogh")
        (Nacionalidad Neerlandes)
        (Estilo "Postimpresionismo")
        (Epoca "1880-1890")
        (Ha_pintado [Cuadro83] [Cuadro84] [Cuadro85] [Cuadro86] [Cuadro87] [Cuadro88] [Cuadro89] [Cuadro90])
    )
    ([Pintor54] of Pintor
        (Nombre "William Hogarth")
        (Nacionalidad Britanico)
        (Estilo "Rococo")
        (Epoca "1720-1764")
        (Ha_pintado [Cuadro48])
    )
    ([Pintor55] of Pintor
        (Nombre "William-Adolphe Bouguereau")
        (Nacionalidad Frances)
        (Estilo "Academicismo")
        (Epoca "1846-1905")
        (Ha_pintado [Cuadro68])
    )
)